language: node_js
node_js:
  - "stable"
addons:
  firefox: "stable"
before_script:
  - npm i -g gulp
  - npm i -g bower
  - bower install
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
script: gulp test
